name: Update ICS

on:
  schedule:
    - cron: "0 3 * * *"  # tous les jours à 3h
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: pip install requests beautifulsoup4 ics pytz

      # 4️⃣ Run script to generate calendar.ics
      - name: Generate ICS
        run: python celcat_to_ics.py

      # 5️⃣ Deploy to gh-pages
      - name: Deploy calendar.ics to gh-pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./          # ton calendar.ics doit être à la racine
          commit_message: "Update calendar.ics"
