name: Update ICS

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install requests beautifulsoup4 ics pytz
      - name: Generate ICS
        run: python celcat_to_ics.py
      - name: Deploy calendar.ics to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_branch: gh-pages
          publish_dir: ./
          commit_message: "Update calendar.ics"
